src/03 - IntegrationTests/src/NerdStore.WebApplication.MVC/Controllers/CartController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalog.Application.Services;
using NerdStore.Core.Messages.CommonMessages;
using NerdStore.Sales.Application.Commands;
using NerdStore.Sales.Application.Queries;

namespace NerdStore.WebApplication.MVC.Controllers
{
    [Authorize]
    public class CartController : ControllerBase
    {
        private readonly IProductAppService _productAppService;
        private readonly IOrderQueries _orderQueries;
        private readonly IMediator _mediatorHandler;

        public CartController(INotificationHandler<DomainNotification> notifications,
                                  IProductAppService productAppService,
                                  IMediator mediatorHandler, 
                                  IOrderQueries orderQueries,
                                  IHttpContextAccessor httpContextAccessor) : base(notifications, mediatorHandler, httpContextAccessor)
        {
            _productAppService = productAppService;
            _mediatorHandler = mediatorHandler;
            _orderQueries = orderQueries;
        }

        [HttpGet]
        [Route("my-cart")]
        public async Task<IActionResult> Index()
        {
            return View(await _orderQueries.GetClientCart(ClientId));
        }

        [HttpPost]
        [Route("my-cart")]
        public async Task<IActionResult> AddItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetById(id);
            if (product == null) return BadRequest();

            if (product.StockQuantity < quantity)
            {
                TempData["Erro"] = "Produto com estoque insuficiente";
                return RedirectToAction("ProductDetail", "Showcase", new { id });
            }

            var command = new AddOrderItemCommand(ClientId, product.Id, product.Name, quantity, product.Price);
            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                return RedirectToAction("Index");
            }

            TempData["Erros"] = GetErrorMessages();
            return RedirectToAction("ProductDetail", "Showcase", new { id });
        }

        [HttpPost]
        [Route("remove-item")]
        public async Task<IActionResult> RemoveItem(Guid id)
        {
            var product = await _productAppService.GetById(id);
            if (product == null) return BadRequest();

            var command = new RemoveOrderItemCommand(ClientId, id);
            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _orderQueries.GetClientCart(ClientId));
        }

        [HttpPost]
        [Route("update-item")]
        public async Task<IActionResult> UpdateItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetById(id);
            if (product == null) return BadRequest();

            var command = new UpdateOrderItemCommand(ClientId, id, quantity);
            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _orderQueries.GetClientCart(ClientId));
        }

        [HttpPost]
        [Route("apply-voucher")]
        public async Task<IActionResult> ApplyVoucher(string voucherCode)
        {
            var command = new ApplyOrderVoucherCommand(ClientId, voucherCode);
            await _mediatorHandler.Send(command);

            if (IsValidOperation())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _orderQueries.GetClientCart(ClientId));
        }

        [HttpGet]
        [Route("purchase-summary")]
        public async Task<IActionResult> PurchaseSummary()
        {
            return View(await _orderQueries.GetClientCart(ClientId));
        }
    }
}

src/03 - IntegrationTests/src/NerdStore.WebApplication.MVC/Extensions/SummaryViewComponent.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Messages.CommonMessages;

namespace NerdStore.WebApplication.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.GetNotifications());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

src/03 - IntegrationTests/src/NerdStore.WebApplication.MVC/Views/Cart/Index.cshtml
@model NerdStore.Sales.Application.Queries.ViewModels.CartViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">

            <vc:summary />

            @{
                if (Model?.Items != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                                <th class="text-center">Valor</th>
                                <th class="text-center">Valor Total</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            @{
                                foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td class="col-sm-5 col-md-5">
                                            <div class="media">
                                                <div class="media-body">
                                                    <h4 class="media-heading"><a asp-controller="Showcase" asp-action="ProductDetail" asp-route-id="@item.ProductId">@item.ProductName</a></h4>
                                                </div>
                                            </div>
                                        </td>

                                        <td class="col-sm-2 col-md-2" style="text-align: center">
                                            <form method="post" asp-controller="Cart" asp-action="UpdateItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <div class="row" style="float: left">
                                                    <input style="width: 70px" type="text" class="form-control" name="quantity" id="quantity" value="@item.Quantity">
                                                </div>
                                                <div class="row" style="float: right">
                                                    <button type="submit" class="btn btn-success">
                                                        <span class="fas fa-sync"></span>
                                                    </button>
                                                </div>
                                            </form>
                                        </td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong id="unitValue">@item.UnitPrice.ToString("C")</strong></td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong id="totalPrice">@item.TotalPrice.ToString("C")</strong></td>

                                        <td class="col-sm-1 col-md-1">
                                            <form method="post" asp-controller="Cart" asp-action="RemoveItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <button type="submit" class="btn btn-danger">
                                                    <span class="fas fa-trash-alt"></span> Remover
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            }

                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td><h5>Subtotal</h5></td>
                                <td class="text-right"><h5><strong>@Model.SubTotal.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td colspan="2">
                                    <form method="post" asp-controller="Cart" asp-action="ApplyVoucher">
                                        <div class="row" style="float: left">
                                            <input placeholder="Voucher" style="width: 150px" type="text" class="form-control" name="VoucherCode" id="VoucherCode" value="@Model.VoucherCode">
                                        </div>
                                        <div class="row" style="float: right">
                                            <button type="submit" class="btn btn-success">
                                                <span class="fas fa-sync"></span>
                                            </button>
                                        </div>
                                    </form>
                                </td>
                                <td><h5>Desconto</h5></td>
                                <td class="text-right"><h5><strong>@Model.DiscountValue.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <h3>Total</h3>
                                </td>
                                <td class="text-right">
                                    <h3><strong>@Model.TotalPrice.ToString("C")</strong></h3>
                                </td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <a asp-controller="Showcase" asp-action="Index" class="btn btn-dark">
                                        <span class="fa fa-shopping-cart"></span>Continuar Compra
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="Cart" asp-action="PurchaseSummary" class="btn btn-success">
                                        <span class="fas fa-play"></span><br /> Finalizar Compra
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }
                else
                {
                    <div><p>Carrinho Vazio</p></div>
                }
            }
        </div>
    </div>
</div>

src/03 - IntegrationTests/src/NerdStore.WebApplication.MVC/Views/Cart/PurchaseSummary.cshtml
@model NerdStore.Sales.Application.Queries.ViewModels.CartViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <vc:summary />

    <div class="row">

        @{
            if (Model.Items.Any())
            {
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Resumo da Compra</span>
                        <span class="badge badge-secondary badge-pill">@Model.Items.Count</span>
                    </h4>
                    <ul class="list-group mb-3">

                        @{
                            foreach (var item in Model.Items)
                            {
                                <li class="list-group-item d-flex justify-content-between lh-condensed">
                                    <div>
                                        <h6 class="my-0">@item.ProductName</h6>
                                        <small class="text-muted">@item.Quantity Unidades</small>
                                    </div>
                                    <span class="text-muted">@item.TotalPrice.ToString("C")</span>
                                </li>
                            }

                            if (!string.IsNullOrEmpty(Model.VoucherCode))
                            {
                                <li class="list-group-item d-flex justify-content-between bg-light">
                                    <div class="text-success">
                                        <h6 class="my-0">Voucher Utilizado</h6>
                                        <small>@Model.VoucherCode</small>
                                    </div>
                                    <span class="text-success">-@Model.DiscountValue.ToString("C")</span>
                                </li>
                            }

                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total</span>
                                <strong>@Model.TotalPrice.ToString("C")</strong>
                            </li>
                        }
                    </ul>

                </div>
                <div class="col-md-8 order-md-1">
                    <form method="post" asp-controller="Cart" asp-action="StartOrder">

                        <h4 class="mb-3">Pagamento</h4>
                        <hr class="mb-4">
                        <div class="row">
                            <img class="img-fluid" src="Images/cards.png">

                        </div>
                        <br /><br />
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label>Nome no Cartão</label>
                                <input asp-for="Payment.CardName" type="text" class="form-control" placeholder="" required="">
                                <small class="text-muted">Nome completo como consta no cartão</small>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label>Número do Cartão</label>
                                <input asp-for="Payment.CardNumber" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label>Data Expiração</label>
                                <input asp-for="Payment.CardExpiration" type="text" class="form-control" placeholder="" required="">
                            </div>
                            <div class="col-md-3 mb-3">
                                <label>CVV</label>
                                <input asp-for="Payment.CardCvv" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Finalizar Compra</button>
                    </form>
                </div>
            }
            else
            {
                <div><p>Carrinho Vazio</p></div>
            }
        }

    </div>
</div>